<?php
/**
 * About — the company history as a timeline.
 *
 * $timeline is the only definition of the entries; edit the array, not the
 * rendered markup. Photos are generated by tools/build-about.py, which also
 * prints the width/height values used here.
 *
 * The business schema deliberately has no foundingDate of 1974: the current
 * business was founded in 2025, and 1974 is the family firm it descends from.
 */

$base             = 'https://vivilakiscranes.gr';
$page_title       = 'Η εταιρεία — Η ιστορία μας από το 1974 | Βιβιλάκης Εμμανουήλ';
$page_description = 'Από έναν γερανό το 1974 σε μια νέα επιχείρηση το 2025: η οικογενειακή ιστορία πίσω από τους Γερανούς και Μεταφορές Βιβιλάκης Εμμανουήλ στο Ηράκλειο Κρήτης.';
$canonical        = $base . '/about';
$og_image         = $base . '/media/about/2025.webp';

$timeline = [
	[
		'year'  => '1974',
		'text'  => 'Ίδρυση της εταιρείας από τον Εμμανουήλ Βιβιλάκη με ένα χωματουργικό μηχάνημα. Λίγους μήνες μετά αγοράστηκε ο πρώτος γερανός και η εταιρεία ξεκινά τη δραστηριότητά της στον χώρο των ανυψώσεων. Ο Εμμανουήλ Βιβιλάκης φεύγει πρόωρα από τη ζωή και την εταιρεία αναλαμβάνουν οι τέσσερις γιοι του. Η εταιρεία χρησιμοποιεί κυρίως τηλεσκοπικούς γερανούς και κλαρκ για χρήση σε λιμάνια και βιομηχανίες.',
		'img'   => '1974', 'w' => 800, 'h' => 583, 'hidpi' => true,
		'alt'   => 'Ασπρόμαυρη φωτογραφία: γερανοφόρο φορτηγό Hydrocon δίπλα σε φορτηγό πλοίο στο λιμάνι',
	],
	[
		'year'  => '2002',
		'text'  => 'Η εταιρεία ανανεώνει τον στόλο της με τους νέους γερανούς παπαγάλους, ενισχύοντας τις δυνατότητές της για πιο απαιτητικά έργα και μεγαλύτερο εύρος εργασιών.',
		'img'   => '2002', 'w' => 323, 'h' => 480, 'hidpi' => false,
		'alt'   => 'Κίτρινος τηλεσκοπικός γερανός με την επιγραφή ΒΙΒΙΛΑΚΗΣ δίπλα σε μεταλλικό πύργο υπό κατασκευή',
	],
	[
		'year'  => '2025',
		'text'  => 'Ο Βιβιλάκης Εμμανουήλ, ο νεότερος, ιδρύει τη δική του εταιρεία, επενδύοντας σε σύγχρονο εξοπλισμό και τεχνογνωσία. Με οδηγό την οικογενειακή παράδοση και όραμα για το μέλλον, η εταιρεία χαράζει μια νέα πορεία, με επαγγελματισμό, εμπειρία και συνέπεια.',
		'img'   => '2025', 'w' => 1120, 'h' => 1400, 'hidpi' => true,
		'alt'   => 'Το πράσινο γερανοφόρο φορτηγό Βιβιλάκης με αρθρωτό γερανό ανυψώνει μεταλλική χοάνη',
	],
];

$about = [
	'@context' => 'https://schema.org',
	'@type' => 'AboutPage',
	'@id' => $canonical . '#page',
	'name' => 'Η εταιρεία',
	'description' => $page_description,
	'url' => $canonical,
	'inLanguage' => 'el',
	'about' => ['@id' => $base . '/#business'],
];

$breadcrumbs = [
	'@context' => 'https://schema.org',
	'@type' => 'BreadcrumbList',
	'itemListElement' => [
		['@type' => 'ListItem', 'position' => 1, 'name' => 'Αρχική', 'item' => $base . '/'],
		['@type' => 'ListItem', 'position' => 2, 'name' => 'Η εταιρεία', 'item' => $canonical],
	],
];

$flags = JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT;
$json_ld = '';
foreach ([$about, $breadcrumbs] as $block) {
	$json_ld .= "\t<script type=\"application/ld+json\">\n" . json_encode($block, $flags) . "\n\t</script>\n";
}

include __DIR__ . '/partials/head.php';
include __DIR__ . '/partials/header.php';
?>

<main id="main">

	<section class="section timeline-section">
		<div class="container">
			<h1 class="sr-only">Η εταιρεία — η ιστορία μας</h1>
			<ol class="timeline">
<?php foreach ($timeline as $i => $t): $f = '/media/about/' . $t['img']; ?>
				<li class="tl-item reveal">
					<div class="tl-media<?= $t['hidpi'] ? '' : ' is-narrow' ?>">
						<img src="<?= e($f) ?><?= $t['hidpi'] ? '-560' : '' ?>.webp"
<?php if ($t['hidpi']): ?>
						     srcset="<?= e($f) ?>-560.webp 560w, <?= e($f) ?>.webp <?= $t['w'] ?>w"
						     sizes="(min-width:860px) 520px, calc(100vw - 96px)"
<?php endif; ?>
						     width="<?= $t['w'] ?>" height="<?= $t['h'] ?>"
						     <?= $i > 0 ? 'loading="lazy" ' : '' ?>decoding="async"
						     alt="<?= e($t['alt']) ?>">
					</div>
					<div class="tl-body">
						<h2 class="tl-year"><?= e($t['year']) ?></h2>
						<p><?= e($t['text']) ?></p>
					</div>
				</li>
<?php endforeach; ?>
			</ol>
		</div>
	</section>

	<section class="section" style="background:var(--surface)">
		<div class="container">
			<div class="section-head center">
				<h2>Χρειάζεστε γερανό για τη δική σας εργασία;</h2>
				<p>Πείτε μας τι θέλετε να ανυψώσετε ή να μεταφέρετε και θα σας προτείνουμε τον κατάλληλο εξοπλισμό.</p>
			</div>
			<div class="hero-ctas" style="justify-content:center;margin-top:0">
				<a class="btn btn-accent" href="/#contact">Ζητήστε προσφορά</a>
				<a class="link-arrow" href="tel:+306949776292">Καλέστε: 6949 776 292 →</a>
			</div>
		</div>
	</section>

</main>

<?php include __DIR__ . '/partials/footer.php'; ?>
